# Problem 2: Even Fibonacci Numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed n, 
# find the sum of the even-valued terms.

def fiboEvenSum(n):
    fibo = [1, 2]
    index, sum= 2, 2
    while fibo[index-1] + fibo[index-2] <= n:
        fibo.append(fibo[index-1] + fibo[index-2])
        if fibo[index] % 2 == 0:
            sum += fibo[index]
        index += 1
    return sum

